# Generated by Django 5.0.6 on 2024-07-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acadebeatmain', '0002_user_auth_provider_user_is_teacher_user_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='dialogjson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
