# Generated by Django 5.0.6 on 2024-07-09 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acadebeatmain', '0003_dialogjson'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dialogjson',
            new_name='dialogjsonmodel',
        ),
    ]
