# Generated by Django 5.0.6 on 2024-07-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acadebeatmain', '0005_dialoguemessage_dialogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
