# Generated by Django 5.0.6 on 2024-07-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acadebeatmain', '0006_user_access_token_user_refresh_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dialogjsonmodel',
        ),
        migrations.RemoveField(
            model_name='dialogue',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='dialogue',
            name='dialogue_id',
        ),
        migrations.RemoveField(
            model_name='dialogue',
            name='id',
        ),
        migrations.AddField(
            model_name='dialogue',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='dialogueId',
            field=models.CharField(default=0, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='DialogueMessage',
        ),
    ]
