# Generated by Django 5.0.6 on 2024-07-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acadebeatmain', '0007_delete_dialogjsonmodel_remove_dialogue_messages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='data',
            field=models.JSONField(),
        ),
    ]
