# Generated by Django 5.0.6 on 2024-07-11 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acadebeatmain', '0008_alter_dialogue_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dialogue',
        ),
    ]
